### ISSUE TITLE
No such operator image::read_file

### ISSUE THREAD

**Issue by S200331082** [sarahESL/PubMedCLIP#7]
hello, me again.
When I ran `main.py`  in `PubMedCLIP` with `vision encoder ViT-B/32`, something wrong:
```
-------Loading CLIP with vision encoder ViT-B/32 -------
-------Training started-------
Traceback (most recent call last):
  File "C:/Users/fhdu/PycharmProjects/PubMedCLIP/main/main.py", line 51, in <module>
    train(cfg, train_loader, val_loader, device)
  File "C:\Users\fhdu\PycharmProjects\PubMedCLIP\main\train.py", line 65, in train
    for i, (image, caption) in enumerate(train_loader):
  File "E:\SoftwareFile\Anaconda3\envs\med_vqa\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "E:\SoftwareFile\Anaconda3\envs\med_vqa\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "E:\SoftwareFile\Anaconda3\envs\med_vqa\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\SoftwareFile\Anaconda3\envs\med_vqa\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\fhdu\PycharmProjects\PubMedCLIP\lib\dataset\ROCOdataset.py", line 80, in __getitem__
    **image = self._load_image(index)**
  File "C:\Users\fhdu\PycharmProjects\PubMedCLIP\lib\dataset\ROCOdataset.py", line 70, in _load_image
    **image = read_image(path, mode=ImageReadMode.RGB)**
  File "E:\SoftwareFile\Anaconda3\envs\med_vqa\lib\site-packages\torchvision\io\image.py", line 222, in read_image
    data = read_file(path)
  File "E:\SoftwareFile\Anaconda3\envs\med_vqa\lib\site-packages\torchvision\io\image.py", line 42, in read_file
    data = torch.ops.image.read_file(path)
  File "E:\SoftwareFile\Anaconda3\envs\med_vqa\lib\site-packages\torch\_ops.py", line 63, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator image::read_file
```

Not sure the wrong version of torch leads to this issue? my version:
torch 1.10.0 , torchvision 0.11.1, according to your `requirement.txt`

Looking forward to your answer, thanks in advance.

**Comment by sarahESL** [comment]
Pytorch version is also dependent to the CUDA version. So the versions in the `requirement.txt` come from the compatibility required for my CUDA version.
Please do try upgrading your Pytorch. I think the error should be resolved by that.

**Comment by S200331082** [comment]
> Pytorch version is also dependent to the CUDA version. So the versions in the `requirement.txt` come from the compatibility required for my CUDA version. Please do try upgrading your Pytorch. I think the error should be resolved by that.

Thanks for your reply, now I have another puzzle: how to generrate the `type_classifier_slake.pth`? use `type_classifier.py`?

**Comment by S200331082** [comment]
it seems to be sure, thanks for such a detailed repository.

> > Pytorch version is also dependent to the CUDA version. So the versions in the `requirement.txt` come from the compatibility required for my CUDA version. Please do try upgrading your Pytorch. I think the error should be resolved by that.
> 
> Thanks for your reply, now I have another puzzle: how to generrate the `type_classifier_slake.pth`? use `type_classifier.py`?
